.DEFAULT_GOAL := help
SHELL := /bin/bash

# Use the venv Python if it exists; otherwise the system one.
VENV ?= .venv
PYTHON := $(if $(wildcard $(VENV)/bin/python),$(VENV)/bin/python,python3)
PIP := $(PYTHON) -m pip

# API base URL and default Discord test message (overridable:
# make publish BASE_URL=http://localhost:8080
# make discord-test MSG="hola comunidad")
BASE_URL ?= http://localhost:8000
MSG ?= Mensaje de prueba de Anfaia Jobs AI 💼

.PHONY: help venv install lint format format-check test test-fast cov \
        run publish discord-test migrate downgrade revision db-up db-down \
        up down build logs ps clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-16s\033[0m %s\n", $$1, $$2}'

# ──────────────────────────────────────────────────────────────────────────
# Environment and dependencies
# ──────────────────────────────────────────────────────────────────────────
venv: ## Create the virtual environment in .venv
	python3 -m venv $(VENV)

install: ## Install the project with dev dependencies
	$(PIP) install --upgrade pip
	$(PIP) install -e ".[dev]"

# ──────────────────────────────────────────────────────────────────────────
# Code quality
# ──────────────────────────────────────────────────────────────────────────
lint: ## Run ruff (linter)
	$(PYTHON) -m ruff check .

format: ## Format the code and auto-fix with ruff
	$(PYTHON) -m ruff format .
	$(PYTHON) -m ruff check --fix .

format-check: ## Check formatting without modifying (as in CI)
	$(PYTHON) -m ruff format --check .
	$(PYTHON) -m ruff check .

# ──────────────────────────────────────────────────────────────────────────
# Tests
# ──────────────────────────────────────────────────────────────────────────
test: ## Run the tests
	$(PYTHON) -m pytest

test-fast: ## Run the tests quietly (faster)
	$(PYTHON) -m pytest -q

cov: ## Generate an HTML coverage report in htmlcov/
	$(PYTHON) -m pytest --cov=app --cov-report=html
	@echo "Report at htmlcov/index.html"

# ──────────────────────────────────────────────────────────────────────────
# Application (local)
# ──────────────────────────────────────────────────────────────────────────
run: ## Start the API locally with autoreload
	$(PYTHON) -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

publish: ## Run the full workflow and publish offers (POST /workflow/run)
	curl -fsS -X POST $(BASE_URL)/workflow/run | $(PYTHON) -m json.tool

discord-test: ## Publish a test message to Discord (usage: make discord-test MSG="...")
	curl -fsS -X POST $(BASE_URL)/discord/test \
		-H 'Content-Type: application/json' \
		-d "$$(printf '{"message":"%s"}' '$(MSG)')" | $(PYTHON) -m json.tool

# ──────────────────────────────────────────────────────────────────────────
# Database / migrations
# ──────────────────────────────────────────────────────────────────────────
migrate: ## Apply migrations up to the latest (upgrade head)
	$(PYTHON) -m alembic upgrade head

downgrade: ## Revert the last migration (downgrade -1)
	$(PYTHON) -m alembic downgrade -1

revision: ## Create an autogenerated migration (usage: make revision m="message")
	$(PYTHON) -m alembic revision --autogenerate -m "$(m)"

db-up: ## Start only PostgreSQL (pgvector) in the background
	docker compose up -d postgres

db-down: ## Stop PostgreSQL
	docker compose stop postgres

# ──────────────────────────────────────────────────────────────────────────
# Docker Compose (full stack)
# ──────────────────────────────────────────────────────────────────────────
build: ## Build the Docker images
	docker compose build

up: ## Start the full stack (app + postgres)
	docker compose up --build

down: ## Stop and remove the containers
	docker compose down

logs: ## Tail the app logs
	docker compose logs -f app

ps: ## List the status of the services
	docker compose ps

# ──────────────────────────────────────────────────────────────────────────
# Utilities
# ──────────────────────────────────────────────────────────────────────────
clean: ## Remove build, cache and coverage artifacts
	rm -rf .pytest_cache .ruff_cache htmlcov .coverage coverage.xml
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type d -name "*.egg-info" -prune -exec rm -rf {} +
